### ISSUE TITLE
Ditch paren-square bracket distinction in syntax

### ISSUE THREAD

**Issue by david-christiansen** [gelisam/klister#15]
Now that I'm writing some more macros, the limitations of our approach to distinguishing fixed-arity vs variable-arity operators is becoming more clear.

In particular, I've been trying to write a quasiquoting macro. This would be used for writing other macros much more conveniently. However, the fixed-arity nature of our square bracket pattern matching operator means that I essentially need to copy-paste the pattern-match cases, once for each length of square-bracketed-list that I want to be able to support. I can't even generate all the cases with a metaprogram :-)

The way I see it, there's two ways forward: (1) eliminate the distinction, or (2) provide variable-arity metaprogramming operators for fixed-arity programs (e.g. a list-like API to the square-bracketed vectors).

Replicating the variable-arity API for fixed-arity things seems to be a failure, so I propose that we do number 1. Any objections?

**Comment by langston-barrett** [comment]
I agree.

**Comment by gelisam** [comment]
I don't have an objection to getting rid of the square parentheses. In fact, I found that it increased friction while writing Klister code. You wrote a lot more Klister code that I did; with time, does it get easier? Does it become helpful?

I disagree that having to provide a list-like API for square brackets is a hint that the square brackets were a mistake. In retrospect, since they can have an arbitrary length, it makes a lot of sense that macros should be allowed to interact with them via a list-like API.

How about the following simplification: `[a b c]` is syntactic sugar for `('[] a b c)`, and it is only a convention that this syntax should be used for fixed-length lists? This way, macros who want to pattern-match on a squared list of a specific length, e.g. `(let1 [x e] body)`, can do so using the pattern `('let1 [x e] body)`, a synonym for the pattern `('let1 ('[] x e) body)`, while macros who want to pattern-match on squared lists of arbitrary length, e.g. `(quasiquote [a ...])`, can do so using the pattern `('quasiquote ('[] . as))`. Most special-case code for square brackets would disappear, except from the parser and from the user-written code which desugars patterns.

**Comment by david-christiansen** [comment]
> with time, does it get easier? Does it become helpful?

I haven't found that the distinction has been helpful, and I have stumbled over it a few times. It's not unusable (modulo concerns about copy-pasting code for various sizes of square-bracketed list), but it doesn't make the language any more pleasant for me to use either.

Your suggestion seems pretty reasonable, though I'd want to give it a name that's easier to type than `'[]`, e.g. `#%vec` by analogy to `#%app`. But I still think that the presence of the feature makes the language more rather than less irritating to use. I've gotten angry a few times that I used the wrong one, and I have not yet had them be helpful.

I don't remember why we put them in to start with - was it just a split-second decision, a "let's see how it goes" experiment, or did we have more reason than a sudden urge during a fevered period of code production?

**Comment by gelisam** [comment]
> I don't remember why we put them in to start with

It was at Compose Conference, you said "we have the opportunity to fix Scheme's mistake" and seemed like you knew what you were doing, so we went ahead without debate.

> it doesn't make the language any more pleasant for me to use either.

Then let's remove it.

**Comment by david-christiansen** [comment]
All right, PR incoming once I please Stack (I'll need to change resolvers to make it happy with `tasty-hedgehog`)
