### ISSUE TITLE
IO monad

### ISSUE THREAD

**Issue by langston-barrett** [gelisam/klister#32]
Yay interactive programs!

**Comment by gelisam** [comment]
At some point we discussed the possibility of providing web-related primitives rather than console-related primitives, to get more bang for our buck. Here's another idea: how about an ffi primitive? By leveraging the [hint](https://github.com/haskell-hint/hint) (which I maintain), we should be able to call any Haskell function from any package (assuming we know the path of the package-db in which that package is installed), which would allow us to support both console-related actions, web-related actions, and more. The biggest difficulty, I think, would be to relate the Haskell types with Klister's types, because both type systems support features which the other type-system doesn't.

**Comment by gelisam** [comment]
Didn't #104 fixed this?

**Comment by gelisam** [comment]
Considering this closed by #104.
